---
version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
    networks:
      - default

  haproxy:
    build: haproxy
    ports:
      - 8080
    networks:
      - default

  hello-go-1:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-2:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-3:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-4:
    build: .
    ports:
      - 8080
    networks:
      - default

  producer:
    build: producer
    networks:
      - default
    links:
      - nginx:gateway

