---
version: "3.7"

services:
  haproxy:
    build: haproxy
    depends_on:
      - hello-go-1
      - hello-go-2
      - hello-go-3
    ports:
      - 8080:8080

  hello-go-1:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-2:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-3:
    build: .
    ports:
      - 8080
    networks:
      - default

  hello-go-4:
    build: .
    ports:
      - 8080
    networks:
      - default

  producer:
    build: producer
    networks:
      - default
    depends_on:
      - hello-go-1
      - hello-go-2
      - hello-go-3
