---
version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:3.5.6-management
    ports:
      - 5672
      - 15672:15672

  haproxy:
    build: haproxy
    depends_on:
      - hello-go-1
      - hello-go-2
      - hello-go-3
    ports:
      - 8080:8080

  hello-go-1:
    build: .
    ports:
      - 8080
    links:
      - rabbitmq:rmq.dev
    networks:
      - default

  hello-go-2:
    build: .
    ports:
      - 8080
    links:
      - rabbitmq:rmq.dev
    networks:
      - default


  hello-go-3:
    build: .
    ports:
      - 8080
    links:
      - rabbitmq:rmq.dev
    networks:
      - default