---
version: "3.7"

services:
  client:
    build: client
    networks:
      - public
    links:
      - nginx:gateway

  nginx:
    build: gateway
    ports:
      - 8080:80
    networks:
      - backend
      - public

  consul-1:
    build: consul
    command: ["agent", "-server", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-node", "consul_1"]
    ports:
      - 8501
      - 8301
    networks:
      - backend

  consul-2:
    build: consul
    command: ["agent", "-server", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-node", "consul_2", "-join", "consul-1"]
    depends_on:
      - consul-1
    ports:
      - 8501
      - 8301
    networks:
      - backend

  consul-3:
    build: consul
    command: ["agent", "-server", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-node", "consul_3", "-join", "consul-1"]
    depends_on:
      - consul-1
    ports:
      - 8501
      - 8301
    networks:
      - backend

  haproxy:
    build: load-balancer
    ports:
      - 8080
    networks:
      - backend

  users-go-1:
    build: users
    ports:
      - 8080
    networks:
      - backend

  users-go-2:
    build: users
    ports:
      - 8080
    networks:
      - backend

  authenticator-go-1:
    build: authenticator
    ports:
      - 8080
    networks:
      - backend

  authenticator-go-2:
    build: authenticator
    ports:
      - 8080
    networks:
      - backend

networks:
  public:
    driver: bridge
  backend:
    driver: bridge

