---
version: "3.7"

services:
  client:
    build: client
    networks:
      - public
    links:
      - nginx:gateway

  nginx:
    build: gateway
    ports:
      - 8080:80
    networks:
      - backend
      - public

  haproxy:
    build: load-balancer
    ports:
      - 8080
    networks:
      - backend

  users-go-1:
    build: users
    ports:
      - 8080
    networks:
      - backend

  users-go-2:
    build: users
    ports:
      - 8080
    networks:
      - backend

  authenticator-go-1:
    build: authenticator
    ports:
      - 8080
    networks:
      - backend

  authenticator-go-2:
    build: authenticator
    ports:
      - 8080
    networks:
      - backend

networks:
  public:
    driver: bridge
  backend:
    driver: bridge

