---
version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - 8080:80
    networks:
      - default

  haproxy:
    build: haproxy
    ports:
      - 8080
    networks:
      - default

  users-go-1:
    build: users
    ports:
      - 8080
    networks:
      - default

  users-go-2:
    build: users
    ports:
      - 8080
    networks:
      - default

  authenticator-go-1:
    build: authenticator
    ports:
      - 8080
    networks:
      - default

  authenticator-go-2:
    build: authenticator
    ports:
      - 8080
    networks:
      - default

  producer:
    build: producer
    networks:
      - default
    links:
      - nginx:gateway

